In [26]:
import keras.backend as k
import numpy as np

In [36]:
a = np.array([[1, 2, 3]])
b = np.array([[1, 1, 1]])
b = np.reshape(b, (3, 1))

In [37]:
a = k.variable(value=a)
b = k.variable(value=b)
sess = k.get_session()

In [38]:
a.eval(session=sess)

array([[ 1.,  2.,  3.]], dtype=float32)

In [39]:
k.dot(a, b).eval(session=sess)

array([[ 6.]], dtype=float32)

In [87]:
x = np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
]], dtype=np.float32) / 10
print(x)
print(x.shape)

[[[ 0.1         0.2         0.30000001]
  [ 0.40000001  0.5         0.60000002]
  [ 0.69999999  0.80000001  0.89999998]
  [ 1.          1.10000002  1.20000005]
  [ 1.29999995  1.39999998  1.5       ]]]
(1, 5, 3)


In [88]:
w = np.array([
    [0.2, 0.5, 0.3]
], dtype=np.float32)
print(w)
print(w.shape)

[[ 0.2         0.5         0.30000001]]
(1, 3)


In [89]:
step_dim = 5
feature_dim = 3

eij = k.reshape(k.dot(k.reshape(x, (-1, feature_dim)), k.reshape(w, (feature_dim, 1))), (-1, step_dim))
print(eij.eval(session=sess))
print(eij.shape)

[[ 0.21000001  0.50999999  0.81000006  1.11000001  1.40999997]]
(1, 5)


In [90]:
eij = k.tanh(eij)
print(eij.eval(session=sess))

[[ 0.20696649  0.46994519  0.66959035  0.80406243  0.88749421]]


In [91]:
a = k.exp(eij)
print(a.eval(session=sess))
print(a.shape)

[[ 1.22994137  1.59990644  1.95343697  2.23460031  2.42903543]]
(1, 5)


In [92]:
a /= k.cast(k.sum(a, axis=1, keepdims=True) + k.epsilon(), k.floatx())
print(a.eval(session=sess))

[[ 0.13019495  0.16935746  0.2067803   0.23654273  0.25712457]]


In [93]:
a = k.expand_dims(a)
print(a.eval(session=sess))
print(a.shape)

[[[ 0.13019495]
  [ 0.16935746]
  [ 0.2067803 ]
  [ 0.23654273]
  [ 0.25712457]]]
(1, 5, 1)


In [94]:
weight_input = x * a
print(weight_input.eval(session=sess))
print(weight_input.shape)

[[[ 0.01301949  0.02603899  0.03905848]
  [ 0.06774299  0.08467873  0.10161448]
  [ 0.14474621  0.16542424  0.18610227]
  [ 0.23654273  0.26019701  0.2838513 ]
  [ 0.33426192  0.35997438  0.38568687]]]
(1, 5, 3)


In [95]:
res = k.sum(weight_input, axis=1)
print(res.eval(session=sess))

[[ 0.79631335  0.89631337  0.99631345]]
